# # GET http://localhost:3000/products/7

# # ###
# # GET http://localhost:3000/product?id_pt=4


# # ###
# # GET http://localhost:3000/usuarios/?correo=c@c.com


# # ###
# # GET http://localhost:3000/products/1

# # ###
# # PUT http://localhost:3000/products/4
# # Content-Type: application/json

# # {"tipo":"hotdogggg","imagen":"HotdogCouple.jpg","id":"4","hidden":0,"deleted":0}

# # ###
# # GET http://localhost:3000/usuarios
# # Content-Type: application/json

# # {
# #     "correo": "c@c.com",
# #     "password": "123"
# # }

# ##
# POST http://localhost:3000/api/register
# Content-Type: application/json

# {
#     "nombre": "Luis",
#     "apellido": "Rodriguez",
#     "correo": "a@a.com",
#     "password": "pass",
#     "telefono": null,
#     "id": 1
# }

# ###
# GET http://localhost:3000/product/17


# ###
# PATCH http://localhost:3000/product/22
# Content-Type: application/json

# {
#     "hidden": 1
# }
# ##
# GET http://localhost:3000/usuarios/?correo=sol@sol.com
# Content-Type: application/json

# {
#     "correo": "sol@sol.com",
#     "pass": "sol"
# }


# ##
# GET http://localhost:3000/usuario/  
# Content-Type: application/json



# ##
# POST http://localhost:3000/api/product
# Content-Type: application/json

# {
#     "nombre" : "Hamburguesa de Queso",
#     "calificacion" : 5,
#     "precio" : 70,
#     "descripcion" : "Pan natural, salchicha Bratwürst colosal, pimiento, cebolla y mayonesa de jalapeño.",
#     "imagen" : "assets/images/BurgerDoubleCheese.jpg",
#     "category" : "5ebb62a59e6c7e436831d0d1",
#     "hidden" : false,
#     "deleted" : false
# }

# ##
# POST http://localhost:3000/api/category
# Content-Type: application/json

# {
#     "tipo": "Hamburguesas",
#     "imagen": "assets/images/BurgerChicken.jpg",
#     "hidden": false,
#     "deleted": false
# }


##
# POST http://localhost:3000/api/cart
# Content-Type: application/json

# {
#     "user_id": 1,
#     "productos": ["5ebb63f7e92a31602b777ffa"],
#     "total": 189
# }

# ##
# GET http://localhost:3000/api/cart/1
# Content-Type: application/json

##
# GET http://localhost:3000/api/pedidos
# Content-Type: application/json

##
POST http://localhost:3000/api/pedido
Content-Type: application/json



###
GET http://localhost:3000/api/category


###
POST http://localhost:3000/api/category
Content-Type: application/json

{
    "id": "2",
    "tipo": "Pizza",
    "imagen": "assets/images/pizza.jpg",
    "hidden": true,
    "deleted": false
}


###
PATCH  http://localhost:3000/api/category/1
Content-Type: application/json

{
    "hidden": true
}


###
GET http://localhost:3000/api/category/1
Content-Type: application/json