GET http://localhost:3000/api/products/

###
GET http://localhost:3000/api/product?id_pt=4


###
GET http://localhost:3000/api/usuarios/?correo=c@c.com


###
GET http://localhost:3000/api/categories/5ebe34fca090dee580829706/products/
Content-Type: application/json

###
PUT http://localhost:3000/api/products/4
Content-Type: application/json

{"tipo":"hotdogggg","imagen":"HotdogCouple.jpg","id":"4","hidden":0,"deleted":0}

###
GET http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "correo": "c@c.com",
    "password": "123"
}

##
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "nombre": "Luis",
    "apellido": "Rodriguez",
    "correo": "a@a.com",
    "password": "pass",
    "telefono": null,
    "id": 1
}

###
GET http://localhost:3000/api/products/17


###
PATCH http://localhost:3000/api/products/22
Content-Type: application/json

{
    "hidden": 1
}

###
GET http://localhost:3000/api/usuarios/?correo=sol@sol.com
Content-Type: application/json

{
    "correo": "sol@sol.com",
    "pass": "sol"
}


###
GET http://localhost:3000/api/usuario/  
Content-Type: application/json

###
POST http://localhost:3000/api/products
Content-Type: application/json

    {
    "nombre": "Cheesecake",
      "calificacion": 5,
      "precio": 50,
      "descripcion": "Delicioso cheesecake con los mejores frutos rojos.",
      "imagen": "./assets/images/PostreCheesecake.jpg",
    "category": "5ebe351ca090dee580829708",
      "hidden":  false,
      "deleted": false
    }
###
POST http://localhost:3000/api/categories
Content-Type: application/json

    {
    "nombre": "Sándwiches",
      "imagen": "public/assets/images/club-sandwich.jpg",
      "hidden": false,
      "deleted": false
    }


###
POST http://localhost:3000/api/carts
Content-Type: application/json

{
    "user_id": "5ebf73eb51c8ead51a05a855",
    "productos": ["5ebb63f7e92a31602b777ffa"],
    "total": 189
}

###
GET http://localhost:3000/api/carts/1
Content-Type: application/json

###
GET http://localhost:3000/api/users/5ec019c7463b3a831d983059/pedidos
Content-Type: application/json

###
GET http://localhost:3000/api/users/5ebf73eb51c8ead51a05a855/carts
Content-Type: application/json

###
POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "user": "5ebf73eb51c8ead51a05a855",
    "products": "5ebf6c869ada6a367068db49",
    "total": "200"
}


###
GET http://localhost:3000/api/categories


###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "tipo": "Pizza",
    "imagen": "public/assets/images/pizza.jpg",
    "hidden": true,
    "deleted": false
}


###
PATCH  http://localhost:3000/api/categories/1
Content-Type: application/json

{
    "hidden": true
}


###
GET http://localhost:3000/api/categories/1
Content-Type: application/json


###
GET http://localhost:3000/api/users/5ebe2f26d6bb888fe0c2702a
Content-Type: application/json